// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int greaterThanHalf = 0 ;
		int lessThanHalf = 0;
		int runs = Integer.parseInt(args[0]);
		for (int i = 0; i < runs; i++) {
			double rand = Math.random();
			if (rand > 0.5) {
				greaterThanHalf++;
			} 
				else {
				lessThanHalf++;
				}
		}
			double ratio;
		System.out.println("> 0.5: " + greaterThanHalf + " times");
		System.out.println("<= 0.5: " + lessThanHalf + " times");
		if (lessThanHalf != 0) {
			ratio = (double) greaterThanHalf / (double) lessThanHalf;
			System.out.println("Ratio: " + ratio);
		}
		
	}
}
